
### Get all users

GET /api/v1/users HTTP/1.1
Host: localhost:8080
Accept: application/json

### Get all chamados

GET /api/v1/chamado HTTP/1.1
Host: localhost:8080
Accept: application/json

### Get chamado

GET /api/v1/chamado/1 HTTP/1.1
Host: localhost:8080
Accept: application/json

### Create a new User

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "batata@potato.com",
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Cria um novo chamado

POST /api/v1/chamado HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "acao": "INSTALAR",
    "objeto": "COMPUTADOR",
    "detalhamento": "Instalar computador na sala 1010",
    "situacao": "NOVO",
    "user": 1
}

### Edita um chamado

PATCH /api/v1/chamado/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "acao": "INSTALAR",
    "objeto": "COMPUTADOR",
    "detalhamento": "Instalar computador na sala 1010",
    "status": "ANDAMENTO",
    "user": 1
}